### PR TITLE
Patch 7

### PR DESCRIPTION
**Pull request by aviraxp**
You rebased on Grarak's source and it doesn't have the commits  you wanted yesterday.....

### CODE REVIEW

**Comment by msfjarvis** [comment]
Authorship?

**Comment by regalstreak** [comment]
We do not need other stuff. This works good.

**Comment by msfjarvis** [comment]
i.e. PR closed?

**Comment by aviraxp** [comment]
OK, the source of the second commit seems come from here https://github.com/AOSPA/android_device_oneplus_oneplus2/commit/4f523150616157ad1e2e4709654832e4032c8205

But close this.

**Comment by xdevs23** [comment]
Looks good to me, at least the first one.

**Comment by regalstreak** [comment]
a,
    a:visited {
        color: #D26000;
        text-decoration: none;
    }


    
        
            
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                            
                        
                    
                
            
            
            
            
                
                    
                        
                 

    
        
            
                
                    
                
            
            
                
                    Join me on PeoplePerHour
                
            
        
        
            
                
                    
                
                
                    Neil is using PeoplePerHour and thinks you need to check it out.
                    Never heard of it? PeoplePerHour is a global freelance hub connecting revolutionaries around the world. Come splash the cash.
                    Your £20 gift will expire in 3 days. Don’t let Neil down... :)
                
            
        
    


                 
                   
                 
                 



    
    	
    		
    			
                	ACCEPT INVITATION
            	
        	
        
    


                 

    
        
            
                Kind Regards,
                The PeoplePerHour Team
            
        
    

                                     
                
            
            
            
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                
                                            
                                        
                                        
                                            
                                                
                                                    
                                                    © 2007 - 2017 PeoplePerHour All rights reserved                                                    
                                                    
                                                        This is an important notification helping you quickly get the most out of PeoplePerHour.  You can change your notification settings here

**Comment by xdevs23** [comment]
@regalstreak advertise one more time and I'll take actions

**Comment by regalstreak** [comment]
a,
    a:visited {
        color: #D26000;
        text-decoration: none;
    }


    
        
            
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                            
                        
                    
                
            
            
            
            
                
                    
                        

    
    
        
          Neil gave you £20 to spend on PeoplePerHour
        
      

      
        
      

      
        
          
          
      
    


	
		Hello,
	
		Neil has been on PeoplePerHour for 5 days and they've invited you to join as well. 
	
		Accept the invitation today and get £20 off your first purchase on PeoplePerHour
	
		



    
    	
    		
    			
                	Join now
            	
        	
        
    


	
		

    
        
            
                Kind Regards,
                The PPH Team
            
        
    



                    
                
            
            
            
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                
                                            
                                        
                                        
                                            
                                                
                                                    
                                                    © 2007 - 2017 PeoplePerHour All rights reserved                                                    
                                                    
                                                        This is an important notification helping you quickly get the most out of PeoplePerHour.  You can change your notification settings here

**Pull request closed without merging**
