### PR TITLE
Use HAL1 for certain apps

### PR DESCRIPTION
**Pull request by aviraxp**
This apps sometimes will have green lines and shadows when taking photos using HAL3.

### CODE REVIEW

**Comment by msfjarvis** [comment]
Looks good to me.. Approved and merged.

**Comment by regalstreak** [comment]
Well I've never got green lines using most of these apps

**Comment by aviraxp** [comment]
Ye, but some people here reported it, try and if breaks something we can revert it

**Comment by xdevs23** [comment]
> Ye, but some people here reported it, try and if breaks something we can revert it

**Official MOTD**

**Pull request merged**
